id: P000671
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-16 16:36:14.988007
source_metadata:
  id: bdr:W1KG17025
  title: ཀོང་ཐེའུ་རང་གི་ར་རྫོང་ཕབ་པ།
  author: ''
  volumes:
    47422c0c3f79457a9d18f26a2f154d17:
      image_group_id: I1KG17063
      title: ''
      volume_number: 1
      total_pages: 196
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
