id: P000671
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG17025
  title: ཀོང་ཐེའུ་རང་གི་ར་རྫོང་ཕབ་པ།
  author: ''
  volumes:
    47422c0c3f79457a9d18f26a2f154d17:
      image_group_id: I1KG17063
      title: ''
      volume_number: 1
      total_pages: 196
