id: I4CF4470A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T20:12:28+00:00'
last_modified: '2022-06-07T12:36:10.254080+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG17025
  title: ཀོང་ཐེའུ་རང་གི་ར་རྫོང་ཕབ་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    88DF:
      image_group_id: I1KG17063
      title: ''
      total_pages: 196
      order: 1
      base_file: 88DF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
